#!/bin/bash

. $OPENSHIFT_REPO_DIR/.openshift/env.sh

cd $OPENSHIFT_REPO_DIR/app/

# migrate to latest database version
java -jar target/backend-0.0.1.jar db migrate kickr.openshift.yml

# start server in background
nohup java -jar target/backend-0.0.1.jar server kickr.openshift.yml > ${OPENSHIFT_DIY_LOG_DIR}/kickr.log 2>&1 &
